buildscript {
    ext.kotlin_version = '2.1.21'
}
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    afterEvaluate { project ->
        if (project.hasProperty('android')) {
            project.android {
                if (namespace == null) {
                    def manifestPath = project.file('src/main/AndroidManifest.xml')
                    if (manifestPath.exists()) {
                        def manifest = new XmlParser().parse(manifestPath)
                        namespace = manifest.@package
                    } else {
                        namespace = project.group
                    }
                }
            }
        }
    }
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
