name: Klxy Build

on:
  push:
    branches:
      - klxy
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-klxy-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "klxy-build"
